// <auto-generated />
using Br.Com.Fiap.Gere.Residuo.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Br.Com.Fiap.Gere.Residuo.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Br.Com.Fiap.Gere.Residuo.Model.AgendaModel", b =>
                {
                    b.Property<int>("AgendaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("agenda_id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AgendaId"));

                    b.Property<int>("BairroId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("bairro_id");

                    b.Property<int>("CaminhaoId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("caminhao_id");

                    b.Property<string>("DiaColetaDeLixo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("dia_coleta_de_lixo");

                    b.Property<int>("MotoristaId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("motorista_id");

                    b.Property<long>("PesoColetadoDeLixoKg")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("peso_coletado_de_lixo_kg");

                    b.Property<string>("StatusColetaDeLixoAgendada")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("status_coleta_de_lixo_agendada");

                    b.Property<string>("TipoResiduo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("tipo_residuo");

                    b.HasKey("AgendaId");

                    b.HasIndex("BairroId");

                    b.HasIndex("CaminhaoId");

                    b.HasIndex("MotoristaId");

                    b.ToTable("T_GR_AGENDA", (string)null);
                });

            modelBuilder.Entity("Br.Com.Fiap.Gere.Residuo.Model.BairroModel", b =>
                {
                    b.Property<int>("BairroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("bairro_id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BairroId"));

                    b.Property<int>("BairroEstaDisponivel")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("bairro_esta_disponivel");

                    b.Property<string>("BairroNome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("bairro_nome");

                    b.Property<int>("PercentualColetaLixoBairro")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("percentual_coleta_lixo_bairro");

                    b.Property<long>("PesoMedioLixeirasKg")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("peso_medio_lixeiras_kg");

                    b.Property<int>("QuantidadeLixeiras")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("quantidade_lixeiras");

                    b.HasKey("BairroId");

                    b.HasIndex("BairroNome")
                        .IsUnique();

                    b.ToTable("T_GR_BAIRRO", (string)null);
                });

            modelBuilder.Entity("Br.Com.Fiap.Gere.Residuo.Model.CaminhaoModel", b =>
                {
                    b.Property<int>("CaminhaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("caminhao_id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CaminhaoId"));

                    b.Property<int>("CaminhaoEstaDisponivel")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("caminhao_esta_disponivel");

                    b.Property<string>("CaminhaoMarca")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("caminhao_marca");

                    b.Property<string>("CaminhaoModelo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("caminhao_modelo");

                    b.Property<string>("CaminhaoPlaca")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("caminhao_placa");

                    b.Property<string>("DataFabricacao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("data_fabricacao");

                    b.HasKey("CaminhaoId");

                    b.HasIndex("CaminhaoPlaca")
                        .IsUnique();

                    b.ToTable("T_GR_CAMINHAO", (string)null);
                });

            modelBuilder.Entity("Br.Com.Fiap.Gere.Residuo.Model.MoradorModel", b =>
                {
                    b.Property<int>("MoradorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("morador_id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MoradorId"));

                    b.Property<int>("BairroId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("bairro_id");

                    b.Property<string>("MoradorEmail")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("morador_email");

                    b.Property<string>("MoradorNome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("morador_nome");

                    b.HasKey("MoradorId");

                    b.HasIndex("BairroId");

                    b.HasIndex("MoradorEmail")
                        .IsUnique();

                    b.ToTable("T_GR_MORADOR", (string)null);
                });

            modelBuilder.Entity("Br.Com.Fiap.Gere.Residuo.Model.MotoristaModel", b =>
                {
                    b.Property<int>("MotoristaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("motorista_id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MotoristaId"));

                    b.Property<string>("MotoristaCpf")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("motorista_cpf");

                    b.Property<int>("MotoristaEstaDisponivel")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("motorista_esta_disponivel");

                    b.Property<string>("MotoristaNome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("motorista_nome");

                    b.Property<string>("MotoristaNrCelular")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("motorista_nr_celular");

                    b.Property<string>("MotoristaNrCelularDdd")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("motorista_nr_celular_ddd");

                    b.Property<string>("MotoristaNrCelularDdi")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("motorista_nr_celular_ddi");

                    b.HasKey("MotoristaId");

                    b.HasIndex("MotoristaCpf")
                        .IsUnique();

                    b.HasIndex("MotoristaNrCelular")
                        .IsUnique();

                    b.ToTable("T_GR_MOTORISTA", (string)null);
                });

            modelBuilder.Entity("Br.Com.Fiap.Gere.Residuo.Model.NotificacaoModel", b =>
                {
                    b.Property<int>("NotificacaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("notificacao_id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificacaoId"));

                    b.Property<int>("AgendaId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("agenda_id");

                    b.HasKey("NotificacaoId");

                    b.HasIndex("AgendaId")
                        .IsUnique();

                    b.ToTable("T_GR_NOTIFICACAO", (string)null);
                });

            modelBuilder.Entity("Br.Com.Fiap.Gere.Residuo.Model.UsuarioModel", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("UsuarioEmail")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("usuario_email");

                    b.Property<string>("UsuarioNome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("usuario_nome");

                    b.Property<string>("UsuarioRole")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("usuario_role");

                    b.Property<string>("UsuarioSenha")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("usuario_senha");

                    b.HasKey("UsuarioId");

                    b.HasIndex("UsuarioEmail")
                        .IsUnique();

                    b.ToTable("T_GR_USUARIO", (string)null);
                });

            modelBuilder.Entity("Br.Com.Fiap.Gere.Residuo.Model.AgendaModel", b =>
                {
                    b.HasOne("Br.Com.Fiap.Gere.Residuo.Model.BairroModel", "BairroAgendadoParaColeta")
                        .WithMany("AgendasDeColetaDeLixoDoBairro")
                        .HasForeignKey("BairroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_T_GR_AGENDA_BAIRRO");

                    b.HasOne("Br.Com.Fiap.Gere.Residuo.Model.CaminhaoModel", "CaminhaoAlocadoParaAgenda")
                        .WithMany("AgendasCriadasComEsteCaminhao")
                        .HasForeignKey("CaminhaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_T_GR_AGENDA_CAMINHAO");

                    b.HasOne("Br.Com.Fiap.Gere.Residuo.Model.MotoristaModel", "MotoristaAlocadoParaAgenda")
                        .WithMany("AgendasCriadasComEsteMotorista")
                        .HasForeignKey("MotoristaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_T_GR_AGENDA_MOTORISTA");

                    b.Navigation("BairroAgendadoParaColeta");

                    b.Navigation("CaminhaoAlocadoParaAgenda");

                    b.Navigation("MotoristaAlocadoParaAgenda");
                });

            modelBuilder.Entity("Br.Com.Fiap.Gere.Residuo.Model.MoradorModel", b =>
                {
                    b.HasOne("Br.Com.Fiap.Gere.Residuo.Model.BairroModel", "BairroDoMorador")
                        .WithMany("MoradoresDoBairro")
                        .HasForeignKey("BairroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_T_GR_MORADOR_BAIRRO");

                    b.Navigation("BairroDoMorador");
                });

            modelBuilder.Entity("Br.Com.Fiap.Gere.Residuo.Model.NotificacaoModel", b =>
                {
                    b.HasOne("Br.Com.Fiap.Gere.Residuo.Model.AgendaModel", "AgendaDaNotificacao")
                        .WithOne("NotificacaoGeradaParaEstaAgenda")
                        .HasForeignKey("Br.Com.Fiap.Gere.Residuo.Model.NotificacaoModel", "AgendaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_T_GR_NOTIFICACAO_AGENDA");

                    b.Navigation("AgendaDaNotificacao");
                });

            modelBuilder.Entity("Br.Com.Fiap.Gere.Residuo.Model.AgendaModel", b =>
                {
                    b.Navigation("NotificacaoGeradaParaEstaAgenda")
                        .IsRequired();
                });

            modelBuilder.Entity("Br.Com.Fiap.Gere.Residuo.Model.BairroModel", b =>
                {
                    b.Navigation("AgendasDeColetaDeLixoDoBairro");

                    b.Navigation("MoradoresDoBairro");
                });

            modelBuilder.Entity("Br.Com.Fiap.Gere.Residuo.Model.CaminhaoModel", b =>
                {
                    b.Navigation("AgendasCriadasComEsteCaminhao");
                });

            modelBuilder.Entity("Br.Com.Fiap.Gere.Residuo.Model.MotoristaModel", b =>
                {
                    b.Navigation("AgendasCriadasComEsteMotorista");
                });
#pragma warning restore 612, 618
        }
    }
}
