name: CI Pipeline - Development

on:
  pull_request:
    branches: 'development'
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      - name: Run Unit Tests
        run: dotnet test ./GereResiduoApiControllerTests/GereResiduoApiControllerTests.csproj